### PR TITLE
Tabbed admin page, channel selector, update readme.

### PR DESCRIPTION
**Pull request by lemsmyth**
First, my apologies for the messy pull request. Still trying to get git and GitHub worked out. I didn't branch enough to have a better organized pull request.
But here's what I have:
- Tabbed pages for the admin section and moved Spee.ch to it's own options array, probably should leave speech available for legacy users? If anyone has a speech instance/account that can test is still working correctly. I don't think I messed with anything related to it other than moving it to a separate options array and moved to separate tab, also put the data through some WP sanitize functions. 
- Removed the channel create options to use the post-admin action to access the $_POST variables for the cURL request, don't think that they need to be saved to the database anyways.? I couldn't get the **Create New Channel** to work while having it on a single page.
- Dropdown selector for setting a default channel on settings page.
- Lowered the amounts of minimum bids to keep more in line with current LBRY Desktop and Odysee low bid amounts. 
- Updated the readme and added some local screenshots with the updated tabbed look.
- Added index.php files to directories to prevent direct access to file structure.
- Added code before classes to exit if access outside WordPress.
- Added an empty array to the wallet_balance request as it is expecting two arguments in the request() method.
- Some code formatting
Not sure what is allowed into a channel name so may need some more sanitizing to remove more characters. Only did a quick search but couldn't find a list of acceptable characters. 
Again apologizes for the mix-match in the diffs, I moved the settings around to organize them and removed the  channel options settings and git is having trouble with re-alining them up correctly.

### CODE REVIEW

**Comment by lemsmyth** [comment]
Not familiar with using Travis CI, but could the build fails be because the Travis CI environment needs the SDK installed or required somehow? Or is that even possible to install into the travis build test? 
I see that there is unit tests in the repo and assume that is what Travis is checking? I've not done unit testing before, I am just guessing and wanted to throw it out there.

**Comment by kauffj** [comment]
Really great to see this is getting picked up. I'm not sure the answer to your CI question above, but we'd like to support this work however we can.

I can bring you into a Discord chat that is developer only if you email me at jeremy@lbry.com.

**Comment by lyoshenka** [comment]
@lemsmyth can you rebase this work into several logical commits so its easier to review? or if its not ready for review yet, let me know.

in general we prefer two ways to do PRs. usually we want one PR to address one issue as a standalone unit of work. alternatively, if you're doing a bunch of small fixes, then make each commit in the PR address one small change and then push the PR once its done. without this focus, its hard to understand what's happening.

**Comment by lemsmyth** [comment]
I will do that, just let me try to figure out how to send only part of the file. I really got messed up in vscodium and couldn't switch branches ended up with this mess. Didn't mean to push it off on you guys, I'll get it fixed.  Hope I can just select sections of code from inside GitHub and separate the PR. I am not very used to working with version control. Just bear with me and I think I can get it figured out and into logical PRs. Not trying to make more work for you than is necessary. I'll close this one then and open some smaller ones.

**Pull request closed without merging**
